/*
 * Copyright (C) 2020 Smirnov Vladimir / mapron1@gmail.com
 * SPDX-License-Identifier: MIT
 * See LICENSE file for details.
 */
#include "LegacyMapping.hpp"

namespace FreeHeroes::Conversion {

const std::vector<std::string> unitIds[2] ={ {
    "sod.unit.pikeman"                    ,
    "sod.unit.halberdier"                 ,
    "sod.unit.archer"                     ,
    "sod.unit.marksman"                   ,
    "sod.unit.griffin"                    ,
    "sod.unit.royalGriffin"               ,
    "sod.unit.swordsman"                  ,
    "sod.unit.crusader"                   ,
    "sod.unit.monk"                       ,
    "sod.unit.zealot"                     ,
    "sod.unit.cavalier"                   ,
    "sod.unit.champion"                   ,
    "sod.unit.angel"                      ,
    "sod.unit.archangel"                  ,
    "sod.unit.centaur"                    ,
    "sod.unit.centaurCaptain"             ,
    "sod.unit.dwarf"                      ,
    "sod.unit.battleDwarf"                ,
    "sod.unit.woodElf"                    ,
    "sod.unit.grandElf"                   ,
    "sod.unit.pegasus"                    ,
    "sod.unit.silverPegasus"              ,
    "sod.unit.dendroidGuard"              ,
    "sod.unit.dendroidSoldier"            ,
    "sod.unit.unicorn"                    ,
    "sod.unit.warUnicorn"                 ,
    "sod.unit.greenDragon"                ,
    "sod.unit.goldDragon"                 ,
    "sod.unit.gremlin"                    ,
    "sod.unit.masterGremlin"              ,
    "sod.unit.stoneGargoyle"              ,
    "sod.unit.obsidianGargoyle"           ,
    "sod.unit.stoneGolem"                 ,
    "sod.unit.ironGolem"                  ,
    "sod.unit.mage"                       ,
    "sod.unit.archMage"                   ,
    "sod.unit.genie"                      ,
    "sod.unit.masterGenie"                ,
    "sod.unit.naga"                       ,
    "sod.unit.nagaQueen"                  ,
    "sod.unit.giant"                      ,
    "sod.unit.titan"                      ,
    "sod.unit.imp"                        ,
    "sod.unit.familiar"                   ,
    "sod.unit.gog"                        ,
    "sod.unit.magog"                      ,
    "sod.unit.hellHound"                  ,
    "sod.unit.cerberus"                   ,
    "sod.unit.demon"                      ,
    "sod.unit.hornedDemon"                ,
    "sod.unit.pitFiend"                   ,
    "sod.unit.pitLord"                    ,
    "sod.unit.efreet"                     ,
    "sod.unit.efreetSultan"               ,
    "sod.unit.devil"                      ,
    "sod.unit.archDevil"                  ,
    "sod.unit.skeleton"                   ,
    "sod.unit.skeletonWarrior"            ,
    "sod.unit.walkingDead"                ,
    "sod.unit.zombieLord"                 ,
    "sod.unit.wight"                      ,
    "sod.unit.wraith"                     ,
    "sod.unit.vampire"                    ,
    "sod.unit.vampireLord"                ,
    "sod.unit.lich"                       ,
    "sod.unit.powerLich"                  ,
    "sod.unit.blackKnight"                ,
    "sod.unit.dreadKnight"                ,
    "sod.unit.boneDragon"                 ,
    "sod.unit.ghostDragon"                ,
    "sod.unit.troglodyte"                 ,
    "sod.unit.infernalTroglodyte"         ,
    "sod.unit.harpy"                      ,
    "sod.unit.harpyHag"                   ,
    "sod.unit.beholder"                   ,
    "sod.unit.evilEye"                    ,
    "sod.unit.medusa"                     ,
    "sod.unit.medusaQueen"                ,
    "sod.unit.minotaur"                   ,
    "sod.unit.minotaurKing"               ,
    "sod.unit.manticore"                  ,
    "sod.unit.scorpicore"                 ,
    "sod.unit.redDragon"                  ,
    "sod.unit.blackDragon"                ,
    "sod.unit.goblin"                     ,
    "sod.unit.hobgoblin"                  ,
    "sod.unit.wolfRider"                  ,
    "sod.unit.wolfHoboRider"              ,
    "sod.unit.orc"                        ,
    "sod.unit.orcChieftain"               ,
    "sod.unit.ogre"                       ,
    "sod.unit.ogreMage"                   ,
    "sod.unit.roc"                        ,
    "sod.unit.thunderbird"                ,
    "sod.unit.cyclop"                     ,
    "sod.unit.cyclopKing"                 ,
    "sod.unit.behemoth"                   ,
    "sod.unit.ancientBehemoth"            ,
    "sod.unit.gnoll"                      ,
    "sod.unit.gnollMarauder"              ,
    "sod.unit.lizardman"                  ,
    "sod.unit.lizardWarrior"              ,
    "sod.unit.gorgon"                     ,
    "sod.unit.mightyGorgon"               ,
    "sod.unit.serpentFly"                 ,
    "sod.unit.dragonFly"                  ,
    "sod.unit.basilisk"                   ,
    "sod.unit.greaterBasilisk"            ,
    "sod.unit.wyvern"                     ,
    "sod.unit.wyvernMonarch"              ,
    "sod.unit.hydra"                      ,
    "sod.unit.chaosHydra"                 ,
    "sod.unit.airElemental"               ,
    "sod.unit.earthElemental"             ,
    "sod.unit.fireElemental"              ,
    "sod.unit.waterElemental"             ,
    "sod.unit.goldGolem"                  ,
    "sod.unit.diamondGolem"               ,
    "sod.unit.pixie"                      ,
    "sod.unit.sprite"                     ,
    "sod.unit.psychicElemental"           ,
    "sod.unit.magicElemental"             ,
    ""                                    ,
    "sod.unit.iceElemental"               ,
    ""                                    ,
    "sod.unit.magmaElemental"             ,
    ""                                    ,
    "sod.unit.stormElemental"             ,
    ""                                    ,
    "sod.unit.energyElemental"            ,
    "sod.unit.firebird"                   ,
    "sod.unit.phoenix"                    ,
    "sod.unit.azureDragon"                ,
    "sod.unit.crystalDragon"              ,
    "sod.unit.fairieDragon"               ,
    "sod.unit.rustDragon"                 ,
    "sod.unit.enchanter"                  ,
    "sod.unit.sharpshooter"               ,
    "sod.unit.halfling"                   ,
    "sod.unit.peasant"                    ,
    "sod.unit.boar"                       ,
    "sod.unit.mummy"                      ,
    "sod.unit.nomad"                      ,
    "sod.unit.rogue"                      ,
    "sod.unit.troll"                      ,
    "sod.unit.catapult"                   ,
    "sod.unit.ballista"                   ,
    "sod.unit.firstAidTent"               ,
    "sod.unit.ammoCart"                   ,
    "sod.unit.arrowTower"                 ,
} ,
{
    "hota.unit.cannon", //150
    "hota.unit.seawolf" ,
    "", // "pikeman" ?

    "hota.unit.nimph"       ,
    "hota.unit.oceanid"     ,
    "hota.unit.crewMate"    ,
    "hota.unit.seaMan"      ,
    "hota.unit.pirate"      ,
    "hota.unit.corsair"     ,
    "hota.unit.stormbird"   ,
    "hota.unit.assid"       ,
    "hota.unit.seaWitch"    ,
    "hota.unit.sorceress"   ,
    "hota.unit.nix"         ,
    "hota.unit.nixWarrior"  ,
    "hota.unit.seaSerpent"  ,
    "hota.unit.haspid"      ,

    "hota.unit.satyr"       ,
    "hota.unit.fangarm"     ,
    "hota.unit.leprechaun"  ,
    "hota.unit.steelGolem"  , //170
} };

const std::vector<std::string> artifactIds[2]= { {
    "sod.artifact.special.spellbook",
    "sod.artifact.special.scroll",
    "sod.artifact.special.grail",
    "sod.artifact.battleMachine.catapult",
    "sod.artifact.battleMachine.ballista",
    "sod.artifact.battleMachine.ammoCart",
    "sod.artifact.battleMachine.firstAidTent",
    "sod.artifact.sword.att2",
    "sod.artifact.sword.att3",
    "sod.artifact.sword.att4",
    "sod.artifact.sword.att5",
    "sod.artifact.sword.att6",
    "sod.artifact.sword.att12",
    "sod.artifact.shield.def2",
    "sod.artifact.shield.def3",
    "sod.artifact.shield.def4",
    "sod.artifact.shield.def5",
    "sod.artifact.shield.def6",
    "sod.artifact.shield.def12",
    "sod.artifact.helm.int1",
    "sod.artifact.helm.int2",
    "sod.artifact.helm.int3",
    "sod.artifact.helm.int4",
    "sod.artifact.helm.int5",
    "sod.artifact.helm.int10",
    "sod.artifact.torso.spl1",
    "sod.artifact.torso.spl2",
    "sod.artifact.torso.spl3",
    "sod.artifact.torso.spl4",
    "sod.artifact.torso.spl5",
    "sod.artifact.torso.spl10",
    "sod.artifact.torso.all1",
    "sod.artifact.boots.all2",
    "sod.artifact.neck.all3",
    "sod.artifact.shield.all4",
    "sod.artifact.sword.all5",
    "sod.artifact.helm.all6",
    "sod.artifact.ring.attDef1",
    "sod.artifact.sword.attDef2",
    "sod.artifact.shield.attDef3",
    "sod.artifact.torso.attDef4",
    "sod.artifact.boots.intSpl1",
    "sod.artifact.cape.intSpl2",
    "sod.artifact.neck.intSpl3",
    "sod.artifact.helm.intSpl4",
    "sod.artifact.ring.luckMorale1",
    "sod.artifact.misc.luck1a",
    "sod.artifact.misc.luck1b",
    "sod.artifact.misc.luck1c",
    "sod.artifact.misc.morale1a",
    "sod.artifact.misc.morale1b",
    "sod.artifact.misc.morale1c",
    "sod.artifact.misc.scoutRadius1a",
    "sod.artifact.misc.scoutRadius1b",
    "sod.artifact.neck.necr1",
    "sod.artifact.cape.necr1",
    "sod.artifact.boots.necr1",
    "sod.artifact.neck.resist1",
    "sod.artifact.cape.resist1",
    "sod.artifact.boots.resist1",
    "sod.artifact.misc.archery1",
    "sod.artifact.misc.archery2",
    "sod.artifact.misc.archery3",
    "sod.artifact.misc.eagle1",
    "sod.artifact.misc.eagle2",
    "sod.artifact.misc.eagle3",
    "sod.artifact.neck.diplomacy1",
    "sod.artifact.ring.diplomacy2",
    "sod.artifact.cape.diplomacy3",
    "sod.artifact.ring.speed1",
    "sod.artifact.ring.mp1",
    "sod.artifact.neck.mp1",
    "sod.artifact.cape.spellFly",
    "sod.artifact.misc.mana1",
    "sod.artifact.misc.mana2",
    "sod.artifact.misc.mana3",
    "sod.artifact.neck.rounds1",
    "sod.artifact.ring.rounds2",
    "sod.artifact.cape.rounds3",
    "sod.artifact.misc.sphereAir",
    "sod.artifact.misc.sphereEarth",
    "sod.artifact.misc.sphereFire",
    "sod.artifact.misc.sphereWater",
    "sod.artifact.cape.noMagic3plus",
    "sod.artifact.misc.neutralizeMorale",
    "sod.artifact.misc.neutralizeLuck",
    "sod.artifact.misc.bookFire",
    "sod.artifact.misc.bookAir",
    "sod.artifact.misc.bookWater",
    "sod.artifact.misc.bookEarth",
    "sod.artifact.boots.spellWalkWater",
    "sod.artifact.misc.archeryNoDistance",
    "sod.artifact.misc.noDispell",
    "sod.artifact.misc.noImmune",
    "sod.artifact.ring.life1a",
    "sod.artifact.ring.life1b",
    "sod.artifact.misc.life2",
    "sod.artifact.neck.speed1",
    "sod.artifact.boots.mp1",
    "sod.artifact.cape.speed2",
    "sod.artifact.neck.protectSpellBers",
    "sod.artifact.neck.protectSpellBlind",
    "sod.artifact.neck.protectSpellCurse",
    "sod.artifact.neck.protectSpellDeathWave",
    "sod.artifact.neck.protectSpellKillUndead",
    "sod.artifact.neck.protectSpellHypnosis",
    "sod.artifact.neck.protectSpellLightning",
    "sod.artifact.neck.protectSpellForget",
    "sod.artifact.neck.luckMorale3",
    "sod.artifact.cape.resourceCrystal",
    "sod.artifact.ring.resourceGems",
    "sod.artifact.misc.resourceCrystal",
    "sod.artifact.misc.resourceOre",
    "sod.artifact.ring.resourceSulfur",
    "sod.artifact.misc.resourceWood",
    "sod.artifact.misc.gold1",
    "sod.artifact.misc.gold2",
    "sod.artifact.misc.gold3",
    "sod.artifact.misc.growth2",
    "sod.artifact.misc.growth3",
    "sod.artifact.misc.growth4",
    "sod.artifact.misc.growth5",
    "sod.artifact.misc.growth6",
    "sod.artifact.helm.boat",
    "sod.artifact.helm.spells5",
    "sod.artifact.misc.noSurrender",
    "sod.artifact.misc.noMagic",
    "sod.artifact.misc.dragonStuff",
    "sod.artifact.sword.armag",
    "sod.artifact.complex.allStat",
    "sod.artifact.complex.necro",
    "sod.artifact.complex.life",
    "sod.artifact.complex.debuff",
    "sod.artifact.complex.growth",
    "sod.artifact.complex.immune",
    "sod.artifact.complex.freeBolt",
    "sod.artifact.complex.fastOnboard",
    "sod.artifact.complex.noBowPenalty",
    "sod.artifact.complex.manaRegen",
    "sod.artifact.complex.spellRounds",
    "sod.artifact.complex.resources", //140

},
 {
    "hota.artifact.complex.diplomacy", // 141
    "hota.artifact.complex.resist",
    "hota.artifact.complex.buff",
    "",
    "",
    "hota.artifact.battleMachine.cannon",
    "hota.artifact.sword.att7",
    "hota.artifact.shield.def7",
    "hota.artifact.torso.spl6",
    "hota.artifact.helm.int6",
    "hota.artifact.boots.pathfind",
    "hota.artifact.misc.unluck1a",
    "hota.artifact.misc.unluck1b",
    "hota.artifact.misc.unluck2",
    "hota.artifact.misc.unmorale1",
    "hota.artifact.ring.unmorale1",
    "hota.artifact.neck.unmorale2",
    "hota.artifact.ring.noResurrect",
    "hota.artifact.cape.noMagic12",
    "hota.artifact.complex.gold",
    "hota.artifact.misc.summon",
    "hota.artifact.misc.interfere",
    "hota.artifact.ring.interfere",
    "hota.artifact.torso.interfere", //164
}
};

const std::vector<std::string> heroesIds[2] = {
    {
    "sod.hero.castle.kn000",
    "sod.hero.castle.kn001",
    "sod.hero.castle.kn002",
    "sod.hero.castle.kn003",
    "sod.hero.castle.kn004",
    "sod.hero.castle.kn005",
    "sod.hero.castle.kn006",
    "sod.hero.castle.kn007",
    "sod.hero.castle.cl008",
    "sod.hero.castle.cl009",
    "sod.hero.castle.cl010",
    "sod.hero.castle.cl011",
    "sod.hero.castle.cl012",
    "sod.hero.castle.cl013",
    "sod.hero.castle.cl014",
    "sod.hero.castle.cl015",
    "sod.hero.rampart.rn016",
    "sod.hero.rampart.rn017",
    "sod.hero.rampart.rn018",
    "sod.hero.rampart.rn019",
    "sod.hero.rampart.rn020",
    "sod.hero.rampart.rn021",
    "sod.hero.rampart.rn022",
    "sod.hero.rampart.rn023",
    "sod.hero.rampart.dr024",
    "sod.hero.rampart.dr025",
    "sod.hero.rampart.dr026",
    "sod.hero.rampart.dr027",
    "sod.hero.rampart.dr028",
    "sod.hero.rampart.dr029",
    "sod.hero.rampart.dr030",
    "sod.hero.rampart.dr031",
    "sod.hero.tower.al032",
    "sod.hero.tower.al033",
    "sod.hero.tower.al034",
    "sod.hero.tower.al035",
    "sod.hero.tower.al036",
    "sod.hero.tower.al037",
    "sod.hero.tower.al038",
    "sod.hero.tower.al039",
    "sod.hero.tower.wz040",
    "sod.hero.tower.wz041",
    "sod.hero.tower.wz042",
    "sod.hero.tower.wz043",
    "sod.hero.tower.wz044",
    "sod.hero.tower.wz045",
    "sod.hero.tower.wz046",
    "sod.hero.tower.wz047",
    "sod.hero.inferno.dm056",
    "sod.hero.inferno.dm057",
    "sod.hero.inferno.dm058",
    "sod.hero.inferno.dm059",
    "sod.hero.inferno.dm060",
    "sod.hero.inferno.dm061",
    "sod.hero.inferno.dm062",
    "sod.hero.inferno.dm063",
    "sod.hero.inferno.hr048",
    "sod.hero.inferno.hr049",
    "sod.hero.inferno.hr050",
    "sod.hero.inferno.hr051",
    "sod.hero.inferno.hr052",
    "sod.hero.inferno.hr053",
    "sod.hero.inferno.hr054",
    "sod.hero.inferno.hr055",
    "sod.hero.necropolis.dk064",
    "sod.hero.necropolis.dk065",
    "sod.hero.necropolis.dk066",
    "sod.hero.necropolis.dk067",
    "sod.hero.necropolis.dk068",
    "sod.hero.necropolis.dk069",
    "sod.hero.necropolis.dk070",
    "sod.hero.necropolis.dk071",
    "sod.hero.necropolis.nc072",
    "sod.hero.necropolis.nc073",
    "sod.hero.necropolis.nc074",
    "sod.hero.necropolis.nc075",
    "sod.hero.necropolis.nc076",
    "sod.hero.necropolis.nc077",
    "sod.hero.necropolis.nc078",
    "sod.hero.necropolis.nc079",
    "sod.hero.dungeon.ov080",
    "sod.hero.dungeon.ov081",
    "sod.hero.dungeon.ov082",
    "sod.hero.dungeon.ov083",
    "sod.hero.dungeon.ov084",
    "sod.hero.dungeon.ov085",
    "sod.hero.dungeon.ov086",
    "sod.hero.dungeon.ov087",
    "sod.hero.dungeon.wl088",
    "sod.hero.dungeon.wl089",
    "sod.hero.dungeon.wl090",
    "sod.hero.dungeon.wl091",
    "sod.hero.dungeon.wl092",
    "sod.hero.dungeon.wl093",
    "sod.hero.dungeon.wl094",
    "sod.hero.dungeon.wl095",
    "sod.hero.stronghold.br096",
    "sod.hero.stronghold.br097",
    "sod.hero.stronghold.br098",
    "sod.hero.stronghold.br099",
    "sod.hero.stronghold.br100",
    "sod.hero.stronghold.br101",
    "sod.hero.stronghold.br102",
    "sod.hero.stronghold.br103",
    "sod.hero.stronghold.bm104",
    "sod.hero.stronghold.bm105",
    "sod.hero.stronghold.bm106",
    "sod.hero.stronghold.bm107",
    "sod.hero.stronghold.bm108",
    "sod.hero.stronghold.bm109",
    "sod.hero.stronghold.bm110",
    "sod.hero.stronghold.bm111",
    "sod.hero.fortress.bs112",
    "sod.hero.fortress.bs113",
    "sod.hero.fortress.bs114",
    "sod.hero.fortress.bs115",
    "sod.hero.fortress.bs116",
    "sod.hero.fortress.bs117",
    "sod.hero.fortress.bs118",
    "sod.hero.fortress.bs119",
    "sod.hero.fortress.wh120",
    "sod.hero.fortress.wh121",
    "sod.hero.fortress.wh122",
    "sod.hero.fortress.wh123",
    "sod.hero.fortress.wh124",
    "sod.hero.fortress.wh125",
    "sod.hero.fortress.wh126",
    "sod.hero.fortress.wh127",
    "sod.hero.conflux.pl000",
    "sod.hero.conflux.pl001",
    "sod.hero.conflux.pl002",
    "sod.hero.conflux.pl003",
    "sod.hero.conflux.pl004",
    "sod.hero.conflux.pl005",
    "sod.hero.conflux.pl006",
    "sod.hero.conflux.pl007",
    "sod.hero.conflux.el000",
    "sod.hero.conflux.el001",
    "sod.hero.conflux.el002",
    "sod.hero.conflux.el003",
    "sod.hero.conflux.el004",
    "sod.hero.conflux.el005",
    "sod.hero.conflux.el006",
    "sod.hero.conflux.el007",
    "sod.hero.castle.kn130",
    "sod.hero.campaign.sh000",
    "sod.hero.campaign.qc128",
    "sod.hero.campaign.sh003",
    "sod.hero.campaign.sh004",
    "sod.hero.campaign.sh005",
    "sod.hero.campaign.sh006",
    "sod.hero.campaign.sh007",
    "sod.hero.campaign.sh009",
    "sod.hero.campaign.sh008",
    "sod.hero.campaign.sh001",
    "sod.hero.campaign.dm131",


},
{
    "hota.hero.cove.plp01",
    "hota.hero.cove.plp02",
    "hota.hero.cove.plp03",
    "hota.hero.cove.plp05",
    "hota.hero.cove.plp06",
    "hota.hero.cove.plp13",
    "hota.hero.cove.plp15",
    "hota.hero.cove.plp16",
    "hota.hero.cove.plp04",
    "hota.hero.cove.plp07",
    "hota.hero.cove.plp08",
    "hota.hero.cove.plp09",
    "hota.hero.cove.plp10",
    "hota.hero.cove.plp11",
    "hota.hero.cove.plp12",
    "hota.hero.cove.plp14",
    "hota.hero.campaign.cvc01",
    "hota.hero.campaign.cvc02",
    "hota.hero.cove.plp17",
    "sod.hero.castle.kx003",
    "sod.hero.fortress.wx122",
    "", // RANLU ?
    "sod.hero.rampart.rx020",

}
};

const std::vector<std::string> skillsIds[2]= {{
    "sod.skill.pathfind",
    "sod.skill.archery",
    "sod.skill.logistics",
    "sod.skill.scouting",
    "sod.skill.diplomacy",
    "sod.skill.navigation",
    "sod.skill.leadership",
    "sod.skill.wisdom",
    "sod.skill.mysticism",
    "sod.skill.luck",
    "sod.skill.ballistics",
    "sod.skill.eagleEye",
    "sod.skill.necromancy",
    "sod.skill.estates",
    "sod.skill.magicFire",
    "sod.skill.magicAir",
    "sod.skill.magicWater",
    "sod.skill.magicEarth",
    "sod.skill.scholar",
    "sod.skill.tactics",
    "sod.skill.artillery",
    "sod.skill.learning",
    "sod.skill.offense",
    "sod.skill.armourer",
    "sod.skill.intelligence",
    "sod.skill.sorcery",
    "sod.skill.resistance",
    "sod.skill.firstAid",
},
{
  "hota.skill.interfere",
}

};

const std::vector<std::string> spellIds[2] = {{
    "sod.spell.summonBoat",
    "sod.spell.scuttleBoat",
    "sod.spell.visions",
    "sod.spell.viewEarth",
    "sod.spell.disguise",
    "sod.spell.viewAir",
    "sod.spell.fly",
    "sod.spell.waterWalk",
    "sod.spell.dimensionDoor",
    "sod.spell.townPortal",
    "sod.spell.quicksand",
    "sod.spell.landMine",
    "sod.spell.forceField",
    "sod.spell.fireWall",
    "sod.spell.earthquake",
    "sod.spell.magicArrow",
    "sod.spell.iceBolt",
    "sod.spell.lightningBolt",
    "sod.spell.implosion",
    "sod.spell.chainLightning",
    "sod.spell.frostRing",
    "sod.spell.fireball",
    "sod.spell.inferno",
    "sod.spell.meteorShower",
    "sod.spell.deathRipple",
    "sod.spell.destroyUndead",
    "sod.spell.armageddon",
    "sod.spell.shield",
    "sod.spell.airShield",
    "sod.spell.fireShield",
    "sod.spell.protectFromAir",
    "sod.spell.protectFromFire",
    "sod.spell.protectFromWater",
    "sod.spell.protectFromEarth",
    "sod.spell.antiMagic",
    "sod.spell.dispel",
    "sod.spell.magicMirror",
    "sod.spell.cure",
    "sod.spell.resurrection",
    "sod.spell.animateDead",
    "sod.spell.sacrifice",
    "sod.spell.bless",
    "sod.spell.curse",
    "sod.spell.bloodLust",
    "sod.spell.precision",
    "sod.spell.weakness",
    "sod.spell.stoneSkin",
    "sod.spell.disruptingRay",
    "sod.spell.prayer",
    "sod.spell.mirth",
    "sod.spell.sorrow",
    "sod.spell.fortune",
    "sod.spell.misfortune",
    "sod.spell.haste",
    "sod.spell.slow",
    "sod.spell.slayer",
    "sod.spell.frenzy",
    "sod.spell.titanBolt",
    "sod.spell.counterstrike",
    "sod.spell.berserk",
    "sod.spell.hypnotize",
    "sod.spell.forgetfulness",
    "sod.spell.blind",
    "sod.spell.teleport",
    "sod.spell.removeObstacle",
    "sod.spell.clone",
    "sod.spell.fireElemental",
    "sod.spell.earthElemental",
    "sod.spell.waterElemental",
    "sod.spell.airElemental",
    "sod.spell.stoneGaze",
    "sod.spell.poison",
    "sod.spell.bind",
    "sod.spell.disease",
    "sod.spell.paralyze",
    "sod.spell.age",
    "sod.spell.deathCloud",
    "sod.spell.thunderbolt",
    "sod.spell.dispelHelpful",
    "sod.spell.deathStare",
    "sod.spell.acidBreath",

},
{


}
};

const std::vector<std::string> classIds[2] = {
    {
    "sod.class.castleF",
    "sod.class.castleM",
    "sod.class.rampartF",
    "sod.class.rampartM",
    "sod.class.towerF",
    "sod.class.towerM",
    "sod.class.infernoF",
    "sod.class.infernoM",
    "sod.class.necropolisF",
    "sod.class.necropolisM",
    "sod.class.dungeonF",
    "sod.class.dungeonM",
    "sod.class.strongholdF",
    "sod.class.strongholdM",
    "sod.class.fortressF",
    "sod.class.fortressM",
    "sod.class.confluxF",
    "sod.class.confluxM",
},
{
    "hota.class.coveF",
    "hota.class.coveM",
}
};


}
